module.exports = {
    registerUser: require('./registerUser'),
    authenticateUserEmail: require('./authenticateUserEmail'),
    authenticateUser: require('./authenticateUser'),
    retrieveUser: require('./retrieveUser'),
    createEvent: require('./createEvent'),
    createEventReview: require('./createEventReview'),
    updateUserProfile: require('./updateUserName'),
    addArtist: require('./addArtist'),
    addPlace: require('./addPlace'),
    updateUserName: require('./updateUserName'),
    updateUserNickName: require('./updateUserNickName'),
    // deleteEvent: require('./deleteEvent'),
    // updateEvent: require('./updateEvent'),
    // toggleLikeEvent: require('./toggleLikeEvent'),
    // toggleFavEvent: require('./toggleFavEvent'),
    // retrieveEvent: require('./retrieveEvent'),
    // retrieveEvents: require('./retrieveEvents'),
    // retrieveLikedEvents: require('./retrieveLikedEvents'),
    // retrieveFavEvents: require('./retrieveFavEvents'),
    // addCommentToEvent: require('./addCommentToEvent'),
    // removeCommentFromEvent: require('./removeCommentFromEvent')
}